apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-todo-db
spec:
  capacity:
    storage: 10Gi
  #volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: scn-todo-db
  hostPath:
    path: /data/pvdb
