apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-todo-db
spec:
  storageClassName: scn-todo-db
  resources:
    requests:
      storage: 10Gi
  #volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
