apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss-todo-db
spec:
  selector:
    matchLabels:
      app: ss-todo-db
  serviceName: ss-todo-db
  replicas: 1
  template:
    metadata:
      labels:
        app: ss-todo-db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        envFrom:
          - configMapRef:
              name: cm-todo-db
        ports:
        - containerPort: 5432
          name: postgres      
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      storageClassName: scn-todo-db
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi