apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-todo-app
  labels:
    app: deploy-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      name: todo-app
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: lemoncodersbc/lc-todo-monolith-db:v5-2024
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: cm-todo-db
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: cm-todo-db
          envFrom:
            - configMapRef:
                name: cm-todo-app
          ports:
            - containerPort: 80
      