apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-todo-app
  labels:
    app: deploy-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      name: todo-app
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: lemoncodersbc/lc-todo-monolith-db:v5-2024
          envFrom:
            - configMapRef:
                name: cm-todo-app
          ports:
            - containerPort: 80
      