apiVersion: batch/v1
kind: Job
metadata:
  name: job-db-migration
spec:
  backoffLimit: 4
  completions: 1
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: sql-runner
          image: postgres:16
          envFrom:
            - configMapRef:
                name: cm-todo-db
          command: ["/bin/sh", "-c"] 
          args: 
            - |
              export PGPASSWORD=$POSTGRES_PASSWORD
              psql -h svc-todo-db -U $POSTGRES_USER -f /sql-script/todos_db.sql
          volumeMounts:
            - name: sql-script-volume
              mountPath: /sql-script
      volumes:
        - name: sql-script-volume
          configMap:
            name: cm-db-migration
      restartPolicy: Never

